### PR TITLE
Upgrade to pydantic v2

### PR DESCRIPTION
**Pull request by gmmajal**
Relevant trello card: https://trello.com/c/eL3fRBPD/210-bump-pydantic-to-version-2-in-qualle

Related to: #18 

The migration to `pydantic` v2 is based on https://docs.pydantic.dev/latest/migration/

The following changes have been introduced in `qualle`:
- `root_validator` is replaced with `model_validator`. More info here: https://docs.pydantic.dev/latest/migration/#validator-and-root_validator-are-deprecated. The recommended syntax is provided here: https://docs.pydantic.dev/latest/concepts/validators/#model-validators.
- `AnyUrl` now does not inherit from class `String` (see here: https://docs.pydantic.dev/latest/migration/#url-and-dsn-types-in-pydanticnetworks-no-longer-inherit-from-str). It is now replaced with a workaround solution (see here: https://github.com/pydantic/pydantic/issues/7186#issuecomment-1820044264).
- `BaseSettings` is imported from a different location. The package `pydantic-settings` has been added inside the `pyproject.toml` file. `BaseSettings` is imported from `pydantic_settings` for `pydantic` v2. More info here: https://docs.pydantic.dev/latest/migration/#basesettings-has-moved-to-pydantic-settings.
- In one instance `Optional[Type]` is provided a default value of `None`. More info here: https://docs.pydantic.dev/latest/migration/#required-optional-and-nullable-fields.
- Additional unit tests have been added to verify model validation behavior. 
  - The unit tests can be found inside `interface/test_config.py` and `test_models.py`
- In order to avoid deprecation errors, `.dict()` and `.json()` are replaced with `model_dump()` and `model_dump_json()`, respectively. More info here: https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel
- An assertion error was being raised inside `interface/test_internal.py`. The dummy subthesauri have now been modified to have a lowercase `URI`.

### CODE REVIEW

**Comment by gmmajal** [comment]
Some refactoring had to be made to comply with our linters in particular `black`. A change has been made in github actions with regards to `flake8`. It will ignore lengthy lines (`E501`).

**Comment by gmmajal** [comment]
The changes from the main branch have been pulled into this feature branch. A new `poetry.lock` file has been created.

**Comment by gmmajal** [comment]
Removed the `ignore` command from the `flake8` job present inside `.github/workflows`

**Comment by gmmajal** [comment]
Post request is working on the local instance of `qualle`. A new unit test has been added to verify the status `422` behavior of our rest api as specified in the `openapi.json` file.

**Review by Lakshmi-bashyam — APPROVED** [review]

**Pull request merged**
